"""End-to-end runner with citation verification and confidence scoring.

Usage:
    python ask.py "How do I reset my password?"
    python ask.py --strategy dense "How do I reset my password?"
    python ask.py --no-verify "How do I reset my password?"
"""
from __future__ import annotations
import argparse
from src.retrieval.dense import retrieve as dense_retrieve
from src.retrieval.sparse import sparse_retrieve
from src.retrieval.fusion import reciprocal_rank_fusion
from src.retrieval.rerank import rerank
from src.answer.generate import answer_question
from src.common.models import RetrievedChunk, ChunkMetadata
from src.ingest.index import get_collection


def hybrid_retrieve(question: str, top_k: int = 5) -> list[RetrievedChunk]:
    """Full hybrid pipeline: dense + sparse → RRF → rerank → top_k."""

    # step 1 — embed the question and find top 20 semantically similar chunks
    dense_results = dense_retrieve(question, top_k=20)

    # step 2 — find top 20 chunks by keyword match using BM25
    sparse_results = sparse_retrieve(question, top_k=20)

    # step 3 — merge both ranked lists into one using RRF
    # chunks appearing high in both lists score highest
    fused = reciprocal_rank_fusion(dense_results, sparse_results)

    # step 4 — fetch the actual chunk text and metadata from Chroma
    # RRF only gives us chunk_ids and scores, not the full chunk content
    col = get_collection()
    fused_chunks = []
    for chunk_id, fused_score in fused[:20]:
        res = col.get(ids=[chunk_id], include=["documents", "metadatas"])
        if not res["ids"]:
            continue
        fused_chunks.append({
            "chunk_id": chunk_id,
            "text": res["documents"][0],
            "metadata": res["metadatas"][0],
            "fused_score": fused_score,
        })

    # step 5 — cross-encoder reads question + chunk together, keeps top 5
    reranked = rerank(question, fused_chunks, top_n=top_k)

    # step 6 — convert plain dicts back into typed RetrievedChunk objects
    out = []
    for c in reranked:
        out.append(RetrievedChunk(
            chunk_id=c["chunk_id"],
            text=c["text"],
            metadata=ChunkMetadata(**c["metadata"]),
            fused_score=c.get("fused_score"),
            rerank_score=c.get("rerank_score"),
        ))
    return out


def print_result(result) -> None:
    """Print the full Answer object including citations and confidence."""

    # answer text generated by Claude Sonnet
    print(f"\n=== Answer ({result.strategy}) ===")
    print(result.answer)

    # each citation with its verification verdict
    if result.citations:
        print("\n=== Citations ===")
        for c in result.citations:
            status = "✅ supported" if c.supported else "❌ unsupported"
            print(f"  [{c.chunk_id}] {status}")
            print(f"    claim:    {c.claim[:80]}{'...' if len(c.claim) > 80 else ''}")
            if c.evidence_span:
                print(f"    evidence: {c.evidence_span[:80]}")

    # claims that failed verification
    if result.unverified:
        print("\n=== Could Not Verify ===")
        print(result.unverified)

    # confidence breakdown — four signals combined into one score
    if result.confidence:
        c = result.confidence
        print("\n=== Confidence ===")
        print(f"  overall:               {c.overall:.2f}")
        print(f"  retrieval score:       {c.retrieval_score:.2f}")
        print(f"  citation support rate: {c.citation_support_rate:.2f}")
        print(f"  completeness:          {c.completeness:.2f}")
        print(f"  no answer flag:        {c.no_answer_flag}")

    # source chunks with their fused scores
    print("\n=== Sources ===")
    for chunk in result.retrieved_chunks:
        score = chunk.fused_score or chunk.dense_score
        score_str = f"{score:.4f}" if score is not None else "n/a"
        print(f"  [{chunk.chunk_id}] {chunk.metadata.source_name}  (score {score_str})")


def main() -> None:
    # parse command line arguments
    parser = argparse.ArgumentParser()
    parser.add_argument("question", nargs="+", help="Question to ask")
    parser.add_argument(
        "--strategy",
        choices=["dense", "hybrid"],
        default="hybrid",
    )
    parser.add_argument(
        "--no-verify",
        action="store_true",
        help="Skip citation verification"
    )
    args = parser.parse_args()
    question = " ".join(args.question)

    # choose retrieval strategy
    if args.strategy == "dense":
        chunks = dense_retrieve(question)
    else:
        chunks = hybrid_retrieve(question)

    # generate answer with optional citation verification
    result = answer_question(
        question=question,
        chunks=chunks,
        strategy=args.strategy,
        verify=not args.no_verify,
    )
    print_result(result)


if __name__ == "__main__":
    main()